### ISSUE TITLE
Migrations do not specify Rails release the migration was written for

### ISSUE THREAD

**Issue by dirkinator** [solidusio-contrib/solidus_related_products#89]
Upon fresh install during the upgrade of my solidus store I found that the generated migration files do not work because the migration does not specify the rails version it was written for.

For me it worked after specifying 4.2 like so:

`class AddPositionToSpreeRelations < ActiveRecord::Migration[4.2]
`
Instead of:

`class AddPositionToSpreeRelations < ActiveRecord::Migration`

**Comment by kennyadsl** [comment]
Hey there! I'm not sure how this is possible since we are not using `ActiveRecord::Migration` in any of our migrations. For example, this is the one you pointed out: https://github.com/solidusio-contrib/solidus_related_products/blob/e5215251aeac016dbdd49640cf8a3cb65d91964a/db/migrate/20130727004612_add_position_to_spree_relations.rb#L3. 

Can you help me understand how you did install the extension to reproduce this issue?

**Comment by Azeem838** [comment]
If you use `gem 'solidus_related_products'` in your gemfile, it will copy the wrong migrations but if you specify the source like this: `gem 'solidus_related_products' , github: 'solidusio-contrib/solidus_related_products'` and you run the installer, it will copy over the correct migrations.

**Comment by kennyadsl** [comment]
This means that we need to release a new version on RubyGems, or update the README here to suggest using the GitHub version.

**Comment by Azeem838** [comment]
@kennyadsl Which one do you suggest is best? I can take care of it

**Comment by kennyadsl** [comment]
Updating the README is best for now IMO, thanks!
